# Gradle Configuration
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# Java Toolchain
systemProp.java.home=/Users/vinipx/Library/Java/JavaVirtualMachines/corretto-23.0.2/Contents/Home