package com.enterprise.taflex.core.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;

/**
 * Central configuration manager for the test automation framework.
 * Loads and provides access to automation.properties.
 * This file is NOT version controlled and is generated by setup.sh
 */
public class ConfigManager {
    
    private static final Logger logger = LoggerFactory.getLogger(ConfigManager.class);
    private static final String CONFIG_FILE = "automation.properties";
    private static final String DEFAULT_CONFIG_FILE = "automation.properties.template";
    
    private static ConfigManager instance;
    private Properties properties;
    
    private ConfigManager() {
        loadProperties();
    }
    
    /**
     * Get singleton instance
     */
    public static synchronized ConfigManager getInstance() {
        if (instance == null) {
            instance = new ConfigManager();
        }
        return instance;
    }
    
    /**
     * Load properties from automation.properties file
     */
    private void loadProperties() {
        properties = new Properties();
        Path configPath = Paths.get(CONFIG_FILE);
        
        if (Files.exists(configPath)) {
            try (InputStream input = new FileInputStream(configPath.toFile())) {
                properties.load(input);
                logger.info("Loaded configuration from {}", CONFIG_FILE);
            } catch (IOException e) {
                logger.error("Failed to load {}", CONFIG_FILE, e);
                throw new RuntimeException("Failed to load configuration: " + e.getMessage(), e);
            }
        } else {
            logger.warn("{} not found. Attempting to load template...", CONFIG_FILE);
            loadDefaultProperties();
        }
        
        // Override with system properties
        properties.putAll(System.getProperties());
    }
    
    /**
     * Load default properties from template
     */
    private void loadDefaultProperties() {
        try (InputStream input = getClass().getClassLoader().getResourceAsStream(DEFAULT_CONFIG_FILE)) {
            if (input != null) {
                properties.load(input);
                logger.info("Loaded default configuration from template");
            } else {
                logger.error("Configuration file {} not found. Run setup.sh first.", CONFIG_FILE);
                throw new RuntimeException("Configuration file not found. Run setup.sh to create it.");
            }
        } catch (IOException e) {
            logger.error("Failed to load default configuration", e);
            throw new RuntimeException("Failed to load default configuration: " + e.getMessage(), e);
        }
    }
    
    /**
     * Get property value as String
     */
    public static String getProperty(String key) {
        return getInstance().properties.getProperty(key);
    }
    
    /**
     * Get property value as String with default
     */
    public static String getProperty(String key, String defaultValue) {
        return getInstance().properties.getProperty(key, defaultValue);
    }
    
    /**
     * Get property value as Integer
     */
    public static int getIntProperty(String key) {
        String value = getProperty(key);
        if (value == null) {
            throw new IllegalArgumentException("Property not found: " + key);
        }
        return Integer.parseInt(value);
    }
    
    /**
     * Get property value as Integer with default
     */
    public static int getIntProperty(String key, int defaultValue) {
        String value = getProperty(key);
        if (value == null) {
            return defaultValue;
        }
        return Integer.parseInt(value);
    }
    
    /**
     * Get property value as Boolean
     */
    public static boolean getBooleanProperty(String key) {
        String value = getProperty(key);
        if (value == null) {
            throw new IllegalArgumentException("Property not found: " + key);
        }
        return Boolean.parseBoolean(value);
    }
    
    /**
     * Get property value as Boolean with default
     */
    public static boolean getBooleanProperty(String key, boolean defaultValue) {
        String value = getProperty(key);
        if (value == null) {
            return defaultValue;
        }
        return Boolean.parseBoolean(value);
    }
    
    /**
     * Get execution mode
     */
    public static String getExecutionMode() {
        return getProperty("execution.mode", "web").toLowerCase();
    }
    
    /**
     * Check if running in headless mode
     */
    public static boolean isHeadless() {
        return getBooleanProperty("web.headless", false);
    }
    
    /**
     * Get timeout value
     */
    public static int getTimeout() {
        return getIntProperty("web.timeout", 30);
    }
    
    /**
     * Get base URL for web tests
     */
    public static String getBaseUrl() {
        return getProperty("web.base.url");
    }
    
    /**
     * Get API base URL
     */
    public static String getApiBaseUrl() {
        return getProperty("api.base.url");
    }
    
    /**
     * Check if ReportPortal is enabled
     */
    public static boolean isReportPortalEnabled() {
        return getBooleanProperty("reportportal.enabled", false);
    }
    
    /**
     * Reload properties (useful for dynamic updates)
     */
    public static void reload() {
        getInstance().loadProperties();
        logger.info("Configuration reloaded");
    }
}